// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechnoByteLambders.MediTrackSensor.Platform.Shared.Infrastructure.Persistence.EFC.Configuration;

#nullable disable

namespace TechnoByteLambders.MediTrackSensor.Platform.Shared.Infrastructure.Persistence.EFC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260610130000_AddDevicesTable")]
    partial class AddDevicesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TechnoByteLambders.MediTrackSensor.Platform.Iam.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("dni");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("entry_date");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("job_title");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("phone");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("photo");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.ToTable("users");
                });

            modelBuilder.Entity("TechnoByteLambders.MediTrackSensor.Platform.Monitoring.Domain.Model.Aggregates.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DoorStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("door_status");

                    b.Property<string>("EnabledSensors")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasDefaultValue("")
                        .HasColumnName("enabled_sensors");

                    b.Property<int>("EstablishmentId")
                        .HasColumnType("int")
                        .HasColumnName("establishment_id");

                    b.Property<string>("ExactLocation")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("exact_location");

                    b.Property<string>("TypeOfMedication")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type_of_medication");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_devices");

                    b.ToTable("devices");

                    b.OwnsOne("TechnoByteLambders.MediTrackSensor.Platform.Monitoring.Domain.Model.ValueObjects.SensorReading", "SensorReading", b1 =>
                        {
                            b1.Property<int>("DeviceId")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<decimal>("AirQuality")
                                .HasPrecision(6, 1)
                                .HasColumnType("decimal(6,1)")
                                .HasColumnName("air_quality");

                            b1.Property<decimal>("AtmosphericPressure")
                                .HasPrecision(6, 2)
                                .HasColumnType("decimal(6,2)")
                                .HasColumnName("atmospheric_pressure");

                            b1.Property<decimal>("Humidity")
                                .HasPrecision(4, 1)
                                .HasColumnType("decimal(4,1)")
                                .HasColumnName("humidity");

                            b1.Property<decimal>("LightIntensity")
                                .HasPrecision(6, 1)
                                .HasColumnType("decimal(6,1)")
                                .HasColumnName("light_intensity");

                            b1.Property<decimal>("SuspendedParticles")
                                .HasPrecision(5, 1)
                                .HasColumnType("decimal(5,1)")
                                .HasColumnName("suspended_particles");

                            b1.Property<decimal>("Temperature")
                                .HasPrecision(4, 1)
                                .HasColumnType("decimal(4,1)")
                                .HasColumnName("temperature");

                            b1.Property<decimal>("Vibration")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("vibration");

                            b1.HasKey("DeviceId")
                                .HasName("p_k_devices");

                            b1.ToTable("devices");

                            b1.WithOwner()
                                .HasForeignKey("DeviceId")
                                .HasConstraintName("f_k_devices_devices_id");
                        });

                    b.Navigation("SensorReading")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
